import { Risk, Control, ComplianceObligation, AuditFinding, AIInsight } from "@/types";

export const MOCK_RISKS: Risk[] = [
  {
    id: "risk-01",
    code: "RSK-CYB-001",
    title: "Sovereign cloud data breach and data leakage via third-party APIs",
    category: "Cyber & IT",
    department: "IT & Security",
    inherentImpact: 4,
    inherentLikelihood: 4,
    residualImpact: 3,
    residualLikelihood: 2,
    trend: "Increasing",
    kriStatus: "Red",
    mitigatingControls: ["ctrl-001", "ctrl-002"],
    appetiteStatus: "Breached",
    owner: "Sarah Jenkins (CISO)",
    lastAssessed: "2026-05-15",
  },
  {
    id: "risk-02",
    code: "RSK-FIN-002",
    title: "Liquidity shortfall and asset-liability mismatch during macro stress",
    category: "Financial",
    department: "Finance",
    inherentImpact: 4,
    inherentLikelihood: 3,
    residualImpact: 2,
    residualLikelihood: 2,
    trend: "Stable",
    kriStatus: "Green",
    mitigatingControls: ["ctrl-003"],
    appetiteStatus: "Within",
    owner: "Marcus Vance (Treasurer)",
    lastAssessed: "2026-05-10",
  },
  {
    id: "risk-03",
    code: "RSK-OPS-003",
    title: "Failure of core core banking mainframe systems due to legacy tech stack",
    category: "Operational",
    department: "Operations",
    inherentImpact: 4,
    inherentLikelihood: 2,
    residualImpact: 3,
    residualLikelihood: 1,
    trend: "Decreasing",
    kriStatus: "Green",
    mitigatingControls: ["ctrl-004"],
    appetiteStatus: "Within",
    owner: "David Karr (COO)",
    lastAssessed: "2026-05-20",
  },
  {
    id: "risk-04",
    code: "RSK-CMP-004",
    title: "Non-compliance with SEC and SOX Section 404 internal reporting controls",
    category: "Compliance",
    department: "Legal",
    inherentImpact: 4,
    inherentLikelihood: 3,
    residualImpact: 2,
    residualLikelihood: 1,
    trend: "Stable",
    kriStatus: "Green",
    mitigatingControls: ["ctrl-005"],
    appetiteStatus: "Within",
    owner: "Elena Rostova (Chief Compliance Officer)",
    lastAssessed: "2026-05-12",
  },
  {
    id: "risk-05",
    code: "RSK-REP-005",
    title: "Reputational damage due to critical customer support outages",
    category: "Reputational",
    department: "Operations",
    inherentImpact: 3,
    inherentLikelihood: 3,
    residualImpact: 2,
    residualLikelihood: 2,
    trend: "Increasing",
    kriStatus: "Amber",
    mitigatingControls: ["ctrl-006"],
    appetiteStatus: "Near Threshold",
    owner: "Aria Thorne (VP of Communications)",
    lastAssessed: "2026-05-18",
  },
  {
    id: "risk-06",
    code: "RSK-CYB-006",
    title: "Insider threat and intellectual property theft via code repository leaks",
    category: "Cyber & IT",
    department: "IT & Security",
    inherentImpact: 3,
    inherentLikelihood: 3,
    residualImpact: 2,
    residualLikelihood: 2,
    trend: "Stable",
    kriStatus: "Amber",
    mitigatingControls: ["ctrl-002"],
    appetiteStatus: "Near Threshold",
    owner: "Sarah Jenkins (CISO)",
    lastAssessed: "2026-05-02",
  },
  {
    id: "risk-07",
    code: "RSK-STR-007",
    title: "Inability to adapt services to digital asset regulation standards",
    category: "Strategic",
    department: "Finance",
    inherentImpact: 3,
    inherentLikelihood: 4,
    residualImpact: 3,
    residualLikelihood: 3,
    trend: "Increasing",
    kriStatus: "Red",
    mitigatingControls: [],
    appetiteStatus: "Breached",
    owner: "Jean-Louis Dupont (Chief Strategy Officer)",
    lastAssessed: "2026-05-25",
  },
  {
    id: "risk-08",
    code: "RSK-FIN-008",
    title: "Interest rate volatility impacting net interest margin (NIM)",
    category: "Financial",
    department: "Finance",
    inherentImpact: 4,
    inherentLikelihood: 3,
    residualImpact: 3,
    residualLikelihood: 2,
    trend: "Stable",
    kriStatus: "Amber",
    mitigatingControls: ["ctrl-003"],
    appetiteStatus: "Near Threshold",
    owner: "Marcus Vance (Treasurer)",
    lastAssessed: "2026-05-28",
  },
  {
    id: "risk-09",
    code: "RSK-OPS-009",
    title: "Key person dependency in quantitative trading algorithms division",
    category: "Operational",
    department: "HR",
    inherentImpact: 3,
    inherentLikelihood: 4,
    residualImpact: 2,
    residualLikelihood: 3,
    trend: "Increasing",
    kriStatus: "Amber",
    mitigatingControls: ["ctrl-007"],
    appetiteStatus: "Near Threshold",
    owner: "Chloe Dupont (VP of HR)",
    lastAssessed: "2026-05-09",
  },
  {
    id: "risk-10",
    code: "RSK-CMP-010",
    title: "Data protection vulnerabilities and GDPR consent management violations",
    category: "Compliance",
    department: "Legal",
    inherentImpact: 4,
    inherentLikelihood: 3,
    residualImpact: 2,
    residualLikelihood: 1,
    trend: "Decreasing",
    kriStatus: "Green",
    mitigatingControls: ["ctrl-008"],
    appetiteStatus: "Within",
    owner: "Elena Rostova (Chief Compliance Officer)",
    lastAssessed: "2026-05-22",
  }
];

export const MOCK_CONTROLS: Control[] = [
  {
    id: "ctrl-001",
    code: "CTL-CYB-101",
    title: "Zero Trust Network Access (ZTNA) with multi-factor authentication",
    riskId: "risk-01",
    type: "Preventative",
    frequency: "Continuous",
    effectiveness: "Effective",
    evidenceStatus: "Submitted",
    evidenceDueDate: "2026-06-01",
    maturityScore: 4.8,
    lastTested: "2026-05-20"
  },
  {
    id: "ctrl-002",
    code: "CTL-CYB-102",
    title: "Real-time API monitoring and automated data-loss prevention (DLP) filters",
    riskId: "risk-01",
    type: "Detective",
    frequency: "Continuous",
    effectiveness: "Ineffective",
    evidenceStatus: "Overdue",
    evidenceDueDate: "2026-05-25",
    deficiencyNote: "DLP software updates failed on 2 nodes, rendering threat indicators out of date.",
    maturityScore: 2.1,
    lastTested: "2026-05-26"
  },
  {
    id: "ctrl-003",
    code: "CTL-FIN-201",
    title: "Automated daily Liquidity Coverage Ratio (LCR) calculation and stress testing",
    riskId: "risk-02",
    type: "Detective",
    frequency: "Daily",
    effectiveness: "Effective",
    evidenceStatus: "Submitted",
    evidenceDueDate: "2026-06-01",
    maturityScore: 4.5,
    lastTested: "2026-05-30"
  },
  {
    id: "ctrl-004",
    code: "CTL-OPS-301",
    title: "Disaster recovery failover simulation and active-active data-center routing",
    riskId: "risk-03",
    type: "Corrective",
    frequency: "Annual",
    effectiveness: "Effective",
    evidenceStatus: "Submitted",
    evidenceDueDate: "2026-11-15",
    maturityScore: 4.2,
    lastTested: "2025-11-12"
  },
  {
    id: "ctrl-005",
    code: "CTL-CMP-401",
    title: "SOX 404 segregation of duties validation engine and monthly ledger audits",
    riskId: "risk-04",
    type: "Preventative",
    frequency: "Monthly",
    effectiveness: "Effective",
    evidenceStatus: "Submitted",
    evidenceDueDate: "2026-06-05",
    maturityScore: 4.6,
    lastTested: "2026-05-05"
  },
  {
    id: "ctrl-006",
    code: "CTL-REP-501",
    title: "Multi-channel redundant customer support platforms with fallback voice support",
    riskId: "risk-05",
    type: "Corrective",
    frequency: "Continuous",
    effectiveness: "Partially Effective",
    evidenceStatus: "Pending",
    evidenceDueDate: "2026-06-10",
    deficiencyNote: "Voice support fallback takes up to 45 seconds to activate during automated service switchover.",
    maturityScore: 3.5,
    lastTested: "2026-05-18"
  },
  {
    id: "ctrl-007",
    code: "CTL-OPS-901",
    title: "Succession planning framework, cross-training logs, and knowledge transfers",
    riskId: "risk-09",
    type: "Preventative",
    frequency: "Quarterly",
    effectiveness: "Ineffective",
    evidenceStatus: "Overdue",
    evidenceDueDate: "2026-05-15",
    deficiencyNote: "Cross-training logs have not been updated since Q3 2025. Key personnel have no trained back-ups.",
    maturityScore: 1.8,
    lastTested: "2026-05-10"
  },
  {
    id: "ctrl-008",
    code: "CTL-CMP-012",
    title: "Automated user consent mapping and cookie ledger audit scripts",
    riskId: "risk-10",
    type: "Detective",
    frequency: "Weekly",
    effectiveness: "Effective",
    evidenceStatus: "Submitted",
    evidenceDueDate: "2026-06-02",
    maturityScore: 4.4,
    lastTested: "2026-05-27"
  }
];

export const MOCK_COMPLIANCE: ComplianceObligation[] = [
  {
    id: "comp-001",
    code: "REG-SOX-404",
    regulation: "SOX 404",
    title: "Internal Control Financial Reporting (ICFR) assurance",
    status: "Compliant",
    completionPct: 100,
    openActions: 0,
    dueDate: "2026-12-31",
    severity: "Critical"
  },
  {
    id: "comp-002",
    code: "REG-GDPR-DP",
    regulation: "GDPR",
    title: "Data protection, consent logs, and Right to be Forgotten processing",
    status: "In Progress",
    completionPct: 82,
    openActions: 3,
    dueDate: "2026-07-15",
    severity: "High"
  },
  {
    id: "comp-003",
    code: "REG-NIST-CSF",
    regulation: "NIST CSF",
    title: "Implement IP address whitelisting, firewalls, and credential cycles",
    status: "Under Review",
    completionPct: 90,
    openActions: 1,
    dueDate: "2026-06-30",
    severity: "High"
  },
  {
    id: "comp-004",
    code: "REG-PCI-DSS",
    regulation: "PCI DSS v4.0",
    title: "Payment gateway transaction ledger encryption and tokenization",
    status: "Compliant",
    completionPct: 100,
    openActions: 0,
    dueDate: "2026-10-01",
    severity: "High"
  },
  {
    id: "comp-005",
    code: "REG-DORA-ICT",
    regulation: "DORA (EU)",
    title: "Digital Operational Resilience Act - ICT risk management framework",
    status: "Non-Compliant",
    completionPct: 45,
    openActions: 7,
    dueDate: "2026-09-30",
    severity: "Critical"
  },
  {
    id: "comp-006",
    code: "REG-ISO-27001",
    regulation: "ISO 27001:2022",
    title: "Information security management system (ISMS) continuous audits",
    status: "In Progress",
    completionPct: 75,
    openActions: 4,
    dueDate: "2026-08-31",
    severity: "Medium"
  }
];

export const MOCK_AUDITS: AuditFinding[] = [
  {
    id: "aud-001",
    code: "AUD-CYB-2025-01",
    auditName: "Q4 2025 Cybersecurity & Access controls",
    findingTitle: "Excessive administrator access privileges in core sovereign database",
    severity: "Critical",
    status: "In Progress",
    recommendation: "Establish a automated Privileged Access Management (PAM) system with Just-In-Time approval cycles.",
    dueDate: "2026-06-15",
    owner: "Sarah Jenkins (CISO)"
  },
  {
    id: "aud-002",
    code: "AUD-FIN-2026-02",
    auditName: "Q1 2026 Treasury Liquidity Stress Testing",
    findingTitle: "Stale macro variables used in interest rate sensitivity forecasts",
    severity: "High",
    status: "Open",
    recommendation: "Integrate Bloomberg terminal API vectors to feed yield curve forecasts in real-time.",
    dueDate: "2026-07-20",
    owner: "Marcus Vance (Treasurer)"
  },
  {
    id: "aud-003",
    code: "AUD-OPS-2026-03",
    auditName: "FY25 Resiliency & Business Continuity Audit",
    findingTitle: "Disaster Recovery hot-site response lagging behind SLA by 12 minutes",
    severity: "High",
    status: "Resolved",
    recommendation: "Deploy server load balancers at the network edge to trigger immediate DNS route shifting.",
    dueDate: "2026-04-30",
    owner: "David Karr (COO)"
  },
  {
    id: "aud-004",
    code: "AUD-GOV-2025-04",
    auditName: "2025 Governance & Committee Oversight",
    findingTitle: "Delays in escalating risk appetite breach notifications to Board Committee",
    severity: "Medium",
    status: "Closed",
    recommendation: "Create automated email and platform escalation triggers in ARAIS when KRI reaches Red thresholds.",
    dueDate: "2026-03-01",
    owner: "Elena Rostova (Compliance)"
  },
  {
    id: "aud-005",
    code: "AUD-HR-2026-05",
    auditName: "Q1 2026 Operational HR Resilience Audit",
    findingTitle: "Lack of backup coverage documentation for algorithmic trading scripts",
    severity: "High",
    status: "Open",
    recommendation: "Mandate peer reviews, documentation uploads, and formal backup assignments in the HR matrix.",
    dueDate: "2026-06-30",
    owner: "Chloe Dupont (VP of HR)"
  }
];

export const MOCK_AI_INSIGHTS: AIInsight[] = [
  {
    id: "ins-001",
    category: "Emerging Risk",
    title: "Digital Asset Regulation Exposure Spike",
    description: "New regulatory draft guidelines released by the ESMA indicate immediate reporting requirements for decentralized products. Potential gap detected in Finance and Legal reporting pathways.",
    impactScore: "Critical",
    timestamp: "2026-05-31T09:12:00Z"
  },
  {
    id: "ins-002",
    category: "Compliance Alert",
    title: "DORA Compliance Lag Detected (45%)",
    description: "Current progression towards the Digital Operational Resilience Act (DORA) deadline is lagging by 18% compared to the peer banking index. Priority focus recommended on establishing third-party risk registers.",
    impactScore: "High",
    timestamp: "2026-05-31T08:45:00Z"
  },
  {
    id: "ins-003",
    category: "Control Deficiency",
    title: "Critical Control CTL-CYB-102 (DLP Filters) Failed",
    description: "Deficiency identified during continuous control testing: DLP signatures are out of date on sovereign database nodes. Exposure exists for credential files and code repositories.",
    impactScore: "High",
    timestamp: "2026-05-30T17:30:00Z"
  },
  {
    id: "ins-004",
    category: "Strategic Recommendation",
    title: "Integrate Bloomberg Yield Curve Inputs",
    description: "Audit recommendation AUD-FIN-2026-02 is due in 50 days. Setting up real-time macro feeds would mitigate interest rate sensitivity errors and resolve operational stress test gaps.",
    impactScore: "Medium",
    timestamp: "2026-05-29T14:10:00Z"
  },
  {
    id: "ins-005",
    category: "Governance Concern",
    title: "KRI Breach Escalation Lag resolved",
    description: "ARAIS alert escalation metrics show the risk committee notification SLA has decreased from 3.2 days to under 4 minutes with automated triggers active.",
    impactScore: "Low",
    timestamp: "2026-05-28T11:00:00Z"
  }
];
